import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Navigation";
import Footer from "./components/footer";
import Script from "next/script"; 
import { ThemeProvider } from "./components/ThemeContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
<html lang="en">
<head>
          {/* ✅ Google reCAPTCHA script */}
          <Script src="https://www.google.com/recaptcha/api.js" strategy="lazyOnload" />
        </head>
      <body
        className={`${inter.className} antialiased`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
    </ThemeProvider>
    
  );
}
